title: "My Notes"
description: "Docs + Math"
theme: null
remote_theme: just-the-docs/just-the-docs
math: katex

plugins:
  - jekyll-remote-theme
baseurl: "/Inverted-Pendulum"

# (khuyến nghị) để URL đúng khi repo là project site
# baseurl: "/TEN-REPO"

# Bật toán (Just the Docs hỗ trợ KaTeX/MathJax qua JS)
# Mỗi trang có thể dùng: math: katex  hoặc  math: mathjax
