title: "My Notes"
description: "Docs + Math"
theme: null
remote_theme: just-the-docs/just-the-docs
math: katex

plugins:
  - jekyll-remote-theme
baseurl: "/Inverted-Pendulum"

just_the_docs:
  custom_css:
    - assets/css/custom.css
